spring.application.name=controle-de-despesas
api.security.token.secret=my-secret-key

# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o Console do H2 no Navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Atualização automática das tabelas pelo JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update